server:
  port: 9898 #????
spring:
  application:
    name: freemarker-demo #?????
  freemarker:
    cache: false  #???????????
    settings:
      template_update_delay: 0 #??????????????0?????????????0?????????????
    suffix: .ftl               #??Freemarker????????
    template-loader-path: classpath:/templates
